swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: javascript:alert(document.domain)//
info:
  version: "0.0.1"
  title: Example Title
  description: Please<a href=//tester40.com/"onmouseover=prompt()//<object data=javascript:alert(9)> Authorize!
paths:
  /:
    get:
      responses:
        200:
          description: Successful response






































